#!/usr/bin/env bash

set -eo pipefail

# -*- coding: utf-8 -*-
# vim:fileencoding=utf-8
# Created by Devyn Collier Johnson
# <DevynCJohnson@Gmail.com>
# http://dcjtech.info/

# Version 2015.02.08
# Public Domain (CC0)
# https://creativecommons.org/publicdomain/zero/1.0/
# http://creativecommons.org/about/cc0

# Version 2020.03.12
# Huan LI (李卓桓) <zixia@zixia.net>
# https://github.com/huan

# https://www.linux.org/threads/running-windows-batch-files-on-linux.11205/

FILE="/tmp/winescript_${$}_$(date '+%s%N').bat"
trap '{ rm -f "${FILE}"; }' EXIT

tail -n +2 "$1" > "$FILE"
wine CMD.EXE /C "$FILE"
echo

exit
